# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
unless User.exists?(id: 1)
  User.create(name: 'Administrador', email: 'guillermo@bitbox.cl', password: 'admin')
end

unless Encuentro.exists?(id: 1)
  Encuentro.create(version: 2017, epigrafe: 'VII Encuentro Internacional de Flauta Traversa', titulo: 'Flauteando en el Río 2019', bajada: 'Conservatorio de Música UACh', vision: 'El Encuentro Internacional de Flauta Traversa “Flauteando en el Río” nace el año 2013 en el Conservatorio de Música de la Facultad de Arquitectura y Artes de la Universidad Austral de Chile (UACh), siendo coordinado y dirigido por la docente del Conservatorio de Música a cargo de la cátedra de flauta traversa, Mg. Florángel Mesko Oberg. La idea de este evento nace como una consecuencia del alto interés que ha generado la enseñanza de este instrumento a nivel regional y nacional. El encuentro se ha transformado en una valiosa experiencia para estudiantes y artistas invitados, ya que genera instancias para compartir y participar en actividades formativas tradicionales como clases individuales y colectivas, y en actividades prácticas que involucran la conformación de ensambles y una orquesta de flautas de estudiantes, a cargo de Mg. Jorge Valdebenito Bertuzi (coordinador musical del encuentro), además de la realización de conciertos. Dentro de las actividades que se realizan en este encuentro se contempla la presentación de estudiantes, académicos y también de invitados nacionales e internacionales donde se ofrece una agenda variada de actividades, de corte formativo-práctico, impartidas por reconocidos intérpretes.', mision: 'Flauteando en el río es una actividad de carácter formativo sin costo de inscripción que tiene por objetivos enriquecer y fortalecer el conocimiento y la práctica de la flauta traversa en distintas áreas, desarrollar técnicas básicas, intermedias y avanzadas en el estudio de la flauta traversa, crear un ambiente de intercambio y aprendizaje entre estudiantes y profesores asistentes al encuentro fomentando la empatía, el trabajo en equipo y el respeto a la diversidad brindando experiencias enriquecedoras a todas las personas que participan.')
end

unless Artista.exists?(id: 1)
  Artista.create(nombre: 'Primer Artista', bio: 'Magna quis excepteur velit nostrud ea velit dolore mollit ullamco. Sit excepteur consectetur elit velit ullamco dolor deserunt ea fugiat mollit. Officia irure aliquip anim sint id adipisicing est. Qui commodo voluptate reprehenderit culpa magna in non qui qui consectetur sit exercitation excepteur. Irure officia proident sint adipisicing occaecat veniam anim incididunt consequat id ut cupidatat ad elit Lorem proident.')
  Artista.create(nombre: 'Segundo Artista', bio: 'Magna quis excepteur velit nostrud ea velit dolore mollit ullamco. Sit excepteur consectetur elit velit ullamco dolor deserunt ea fugiat mollit. Officia irure aliquip anim sint id adipisicing est. Qui commodo voluptate reprehenderit culpa magna in non qui qui consectetur sit exercitation excepteur. Irure officia proident sint adipisicing occaecat veniam anim incididunt consequat id ut cupidatat ad elit Lorem proident.')
  Artista.create(nombre: 'Tercer Artista', bio: 'Magna quis excepteur velit nostrud ea velit dolore mollit ullamco. Sit excepteur consectetur elit velit ullamco dolor deserunt ea fugiat mollit. Officia irure aliquip anim sint id adipisicing est. Qui commodo voluptate reprehenderit culpa magna in non qui qui consectetur sit exercitation excepteur. Irure officia proident sint adipisicing occaecat veniam anim incididunt consequat id ut cupidatat ad elit Lorem proident.')
  Artista.create(nombre: 'Cuarto Artista', bio: 'Magna quis excepteur velit nostrud ea velit dolore mollit ullamco. Sit excepteur consectetur elit velit ullamco dolor deserunt ea fugiat mollit. Officia irure aliquip anim sint id adipisicing est. Qui commodo voluptate reprehenderit culpa magna in non qui qui consectetur sit exercitation excepteur. Irure officia proident sint adipisicing occaecat veniam anim incididunt consequat id ut cupidatat ad elit Lorem proident.')
end
